///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class TableModel {
/*
{
  "id": 1,
  "clubName": "«Altyn Asyr»",
  "image": "/uploads/game/2023-06-04T13-20-44.429Z_Altyn Asyr FC.png",
  "status": "football",
  "totalGoals": 2,
  "lose": 0,
  "win": 1,
  "draw": 0,
  "totalMatches": 1,
  "score": 3,
  "totalRedCards": 0,
  "totalYellowCards": 0
} 
*/

  int? id;
  String? clubName;
  String? image;
  String? status;
  int? totalGoals;
  int? lose;
  int? win;
  int? draw;
  int? totalMatches;
  int? score;
  int? totalRedCards;
  int? totalYellowCards;

  TableModel({
    this.id,
    this.clubName,
    this.image,
    this.status,
    this.totalGoals,
    this.lose,
    this.win,
    this.draw,
    this.totalMatches,
    this.score,
    this.totalRedCards,
    this.totalYellowCards,
  });
  TableModel.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    clubName = json['clubName']?.toString();
    image = json['image']?.toString();
    status = json['status']?.toString();
    totalGoals = json['totalGoals']?.toInt();
    lose = json['lose']?.toInt();
    win = json['win']?.toInt();
    draw = json['draw']?.toInt();
    totalMatches = json['totalMatches']?.toInt();
    score = json['score']?.toInt();
    totalRedCards = json['totalRedCards']?.toInt();
    totalYellowCards = json['totalYellowCards']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['clubName'] = clubName;
    data['image'] = image;
    data['status'] = status;
    data['totalGoals'] = totalGoals;
    data['lose'] = lose;
    data['win'] = win;
    data['draw'] = draw;
    data['totalMatches'] = totalMatches;
    data['score'] = score;
    data['totalRedCards'] = totalRedCards;
    data['totalYellowCards'] = totalYellowCards;
    return data;
  }
}
